version: "3"

services:
  db:
    image: mongo
    env_file:
      - .env
    volumes:
      - ./mongo_data/:/data/db
    ports:
      - "27018:27017"
  web_app:
    build:
      dockerfile: Dockerfile
      context: .
    extra_hosts:
      - "host.docker.internal:host-gateway"
    image: pedrojunqueira/fastapi-bus
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "80:80"
