version: "3"

services:
  # db:
  #   image: mongodb
  #   env_file:
  #     - .env
  web_app:
    build:
      dockerfile: Dockerfile
      context: .
    image: pedrojunqueira/fastapi-bus
    env_file:
      - .env
    # depends_on:
    #   - db
    ports:
      - "80:80"
